# Generated by Django 2.2.4 on 2019-09-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190903_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
